project:
  type: website

website:
  title: "Initiatives numériques"
  navbar:
    title: "Initiatives numériques"
    background: "#f7f7f4"
    foreground: "#2c6b67"
    pinned: true
    right:
      - text: "Blog"
        file: index.qmd
      - text: "Projets"
        file: projets.qmd
      - text: "L'auteur du site"
        file: about.qmd
  page-footer: 
    left: 
      Site réalisé avec
      [Quarto](https://www.quarto.org/)
      | Police de caractères
      [Luciole](https://luciole-vision.com)
    center: 
      - droits.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/design4data
      - icon: github
        href: https://github.com/design4data
      - icon: linkedin
        href: https://www.linkedin.com/in/sylviemeunier

format:
  html:
    theme: [litera, styles.scss]
    highlight-style: a11y-dark
    toc: true
    toc-depth: 4
    toc-location: left
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
    code-copy: true

execute:
    warning: false
    message: false

editor: visual



